site_name: Project CodeGuard
site_description: Project CodeGuard is an AI model-agnostic security framework and ruleset that embeds secure-by-default practices into AI coding workflows (generation and review). It ships core security rules, translators for popular coding agents, and validators to test rule compliance.
site_author: Cisco AI-enabled Security Engineering, Security and Trust
site_url: https://project-codeguard.org

theme:
  name: material
  # logo: assets/placeholder_codeguard.png
  # favicon: assets/placeholder_codeguard.png
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
repo_url: https://github.com/project-codeguard/rules
repo_name: project-codeguard/rules
# edit_uri: ""

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - FAQ: faq.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
      
extra:
  generator: false

